steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file
      - agentic-studio-functional-demo/backend/Dockerfile
      - --tag
      - "${_IMAGE}"
      - .
  - name: gcr.io/cloud-builders/docker
    args: ["push", "${_IMAGE}"]
images:
  - "${_IMAGE}"
